/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bridgelabz.hotelreservationsystem;

import org.junit.Test;

import com.bridgelabz.hotelreservationsystem.Hotel;

import static org.junit.Assert.*;

import org.junit.Assert;

public class HotelReservationTest {
    @Test public void addHotel_correctDetailsOfHotel_True(){
    	ListOfHotels listOfHotels=new ListOfHotels();
    	Hotel hotel=new Hotel("Lakewood", 120.0);
    	boolean added=listOfHotels.addHotel(hotel);
    	Assert.assertEquals(added,true);
    	
    	
    }
    
    @Test public void findCheapestHotel_differentHotelsWithDifferentRates_CheapestHotel() {
    	ListOfHotels listOfHotels=new ListOfHotels();
    	Hotel hotel1=new Hotel("Lakewood", 110.0);
    	Hotel hotel2=new Hotel("Bridgewood", 90.0);
    	Hotel hotel3=new Hotel("Ridgewood", 80.0);
    }
}
