/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bridgelabz.hotelreservationsystem;

import org.junit.Test;

import com.bridgelabz.hotelreservationsystem.Hotel;

import static org.junit.Assert.*;

public class HotelReservationTest {
    @Test public void testSomeLibraryMethod() {
        Hotel classUnderTest = new Hotel();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
