/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bridgelabz.hotelreservationsystem;

public class Hotel {
    private String nameOfHotel;
    private double weekdayRates;
    private double weekendRates;
    
    public String getNameOfHotel() {
		return nameOfHotel;
	}
	public void setNameOfHotel(String nameOfHotel) {
		this.nameOfHotel = nameOfHotel;
	}
	public double getWeekdayRates() {
		return weekdayRates;
	}
	public void setWeekdayRates(double weekdayRates) {
		this.weekdayRates = weekdayRates;
	}
	public double getWeekendRates() {
		return weekendRates;
	}
	public void setWeekendRates(double weekendRates) {
		this.weekendRates = weekendRates;
	}
	
    
}
