/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bridgelabz.hotelreservationsystem;

public class Hotel {
    public boolean someLibraryMethod() {
        return true;
    }
}
