/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bridgelabz.hotelreservationsystem;

public class Hotel {
    private String nameOfHotel;
    private double rates;

	public Hotel(String name, double rates) {
		this.nameOfHotel=name;
		this.rates=rates;
	}
    
    public String getNameOfHotel() {
		return nameOfHotel;
	}
	public void setNameOfHotel(String nameOfHotel) {
		this.nameOfHotel = nameOfHotel;
	}

	public double getRates() {
		return rates;
	}

	public void setRates(double rates) {
		this.rates = rates;
	}
	
    
}
